#!/bin/bash 
for iter in {1..4..1}
{
  python ./rrsg_cgreco/_Init_CG.py --data=rawdata_brain_radial_96proj_12ch.h5 --ogf=1.706 --acc=$iter
}
for iter in {1..4..1}
{
  python ./rrsg_cgreco/_Init_CG.py --data=rawdata_heart_radial_55proj_34ch.h5 --ogf=1+1/3 --acc=$iter
}

python ./rrsg_cgreco/plot_results.py
